package client

import (
	"fmt"
	"testing"
)

func TestJson(t *testing.T) {
	data := `{
    "applications":{
        "application":[
            {
                "name":"OTMGROUP-OPENAPI-GATEWAY",
                "instance":[
                    {
                        "instanceId":"172.16.32.8:otmgroup-openapi-gateway:8888",
                        "hostName":"172.16.32.8",
                        "app":"OTMGROUP-OPENAPI-GATEWAY",
                        "ipAddr":"172.16.32.8",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8888,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1625221252751,
                            "lastRenewalTimestamp":1628758062395,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1623141596742
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8888"
                        },
                        "homePageUrl":"http://172.16.32.8:8888/",
                        "statusPageUrl":"http://172.16.32.8:8888/actuator/info",
                        "healthCheckUrl":"http://172.16.32.8:8888/actuator/health",
                        "vipAddress":"otmgroup-openapi-gateway",
                        "secureVipAddress":"otmgroup-openapi-gateway",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1625221252751",
                        "lastDirtyTimestamp":"1625221252572",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"UNIONBUY-MEMBER-LIFENG",
                "instance":[
                    {
                        "instanceId":"172.16.0.17:unionbuy-member-lifeng:9061",
                        "hostName":"172.16.0.17",
                        "app":"UNIONBUY-MEMBER-LIFENG",
                        "ipAddr":"172.16.0.17",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9061,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216882,
                            "lastRenewalTimestamp":1628758058767,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999193417
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9061"
                        },
                        "homePageUrl":"http://172.16.0.17:9061/",
                        "statusPageUrl":"http://172.16.0.17:9061/actuator/info",
                        "healthCheckUrl":"http://172.16.0.17:9061/actuator/health",
                        "vipAddress":"unionbuy-member-lifeng",
                        "secureVipAddress":"unionbuy-member-lifeng",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216882",
                        "lastDirtyTimestamp":"1621999193412",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-GATEWAY",
                "instance":[
                    {
                        "instanceId":"172.16.0.7:otmgroup-gateway:9200",
                        "hostName":"172.16.0.7",
                        "app":"OTMGROUP-GATEWAY",
                        "ipAddr":"172.16.0.7",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9200,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216185,
                            "lastRenewalTimestamp":1628758054983,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999216185
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300"
                        },
                        "homePageUrl":"http://172.16.0.7:9200/",
                        "statusPageUrl":"http://172.16.0.7:8099/info",
                        "healthCheckUrl":"http://172.16.0.7:8099/health",
                        "vipAddress":"otmgroup-gateway",
                        "secureVipAddress":"otmgroup-gateway",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216185",
                        "lastDirtyTimestamp":"1611114703760",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-GOODS",
                "instance":[
                    {
                        "instanceId":"172.16.32.7:hotel-operation-platform-goods:9222",
                        "hostName":"172.16.32.7",
                        "app":"HOTEL-OPERATION-PLATFORM-GOODS",
                        "ipAddr":"172.16.32.7",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9222,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628529555584,
                            "lastRenewalTimestamp":1628758055184,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1628152917756
                        },
                        "metadata":{
                            "management.port":"9222"
                        },
                        "homePageUrl":"http://172.16.32.7:9222/",
                        "statusPageUrl":"http://172.16.32.7:9222/actuator/info",
                        "healthCheckUrl":"http://172.16.32.7:9222/actuator/health",
                        "vipAddress":"hotel-operation-platform-goods",
                        "secureVipAddress":"hotel-operation-platform-goods",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628529555584",
                        "lastDirtyTimestamp":"1628529555357",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-MEMBER",
                "instance":[
                    {
                        "instanceId":"172.16.32.4:hotel-operation-platform-member:8091",
                        "hostName":"172.16.32.4",
                        "app":"HOTEL-OPERATION-PLATFORM-MEMBER",
                        "ipAddr":"172.16.32.4",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8091,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628751759210,
                            "lastRenewalTimestamp":1628758059517,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1628585373514
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8091"
                        },
                        "homePageUrl":"http://172.16.32.4:8091/",
                        "statusPageUrl":"http://172.16.32.4:8091/actuator/info",
                        "healthCheckUrl":"http://172.16.32.4:8091/actuator/health",
                        "vipAddress":"hotel-operation-platform-member",
                        "secureVipAddress":"hotel-operation-platform-member",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628751759210",
                        "lastDirtyTimestamp":"1628751758823",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-MERCHANT-MINIPROGRAM",
                "instance":[
                    {
                        "instanceId":"172.16.32.5:hotel-operation-platform-merchant-miniprogram:8012",
                        "hostName":"172.16.32.5",
                        "app":"HOTEL-OPERATION-PLATFORM-MERCHANT-MINIPROGRAM",
                        "ipAddr":"172.16.32.5",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8012,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1625129758445,
                            "lastRenewalTimestamp":1628758064405,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1625128155715
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8012"
                        },
                        "homePageUrl":"http://172.16.32.5:8012/",
                        "statusPageUrl":"http://172.16.32.5:8012/actuator/info",
                        "healthCheckUrl":"http://172.16.32.5:8012/actuator/health",
                        "vipAddress":"hotel-operation-platform-merchant-miniprogram",
                        "secureVipAddress":"hotel-operation-platform-merchant-miniprogram",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1625129758445",
                        "lastDirtyTimestamp":"1625129757964",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-MERCHANT",
                "instance":[
                    {
                        "instanceId":"172.16.32.9:hotel-operation-platform-merchant:9001",
                        "hostName":"172.16.32.9",
                        "app":"HOTEL-OPERATION-PLATFORM-MERCHANT",
                        "ipAddr":"172.16.32.9",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9001,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628679442921,
                            "lastRenewalTimestamp":1628758049201,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1628001270243
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9001"
                        },
                        "homePageUrl":"http://172.16.32.9:9001/",
                        "statusPageUrl":"http://172.16.32.9:9001/actuator/info",
                        "healthCheckUrl":"http://172.16.32.9:9001/actuator/health",
                        "vipAddress":"hotel-operation-platform-merchant",
                        "secureVipAddress":"hotel-operation-platform-merchant",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628679442921",
                        "lastDirtyTimestamp":"1628679442678",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"APOLLO-ADMINSERVICE",
                "instance":[
                    {
                        "instanceId":"172.16.0.11:apollo-adminservice:9091",
                        "hostName":"172.16.0.11",
                        "app":"APOLLO-ADMINSERVICE",
                        "ipAddr":"172.16.0.11",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9091,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999214993,
                            "lastRenewalTimestamp":1628758076324,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999214993
                        },
                        "metadata":{
                            "management.port":"9091"
                        },
                        "homePageUrl":"http://172.16.0.11:9091/",
                        "statusPageUrl":"http://172.16.0.11:9091/info",
                        "healthCheckUrl":"http://172.16.0.11:9091/health",
                        "vipAddress":"apollo-adminservice",
                        "secureVipAddress":"apollo-adminservice",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999214993",
                        "lastDirtyTimestamp":"1621999214990",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-MESSAGE",
                "instance":[
                    {
                        "instanceId":"172.16.32.10:hotel-operation-platform-message:9798",
                        "hostName":"172.16.32.10",
                        "app":"HOTEL-OPERATION-PLATFORM-MESSAGE",
                        "ipAddr":"172.16.32.10",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9798,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1623210814465,
                            "lastRenewalTimestamp":1628758053571,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999195313
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9798"
                        },
                        "homePageUrl":"http://172.16.32.10:9798/",
                        "statusPageUrl":"http://172.16.32.10:9798/actuator/info",
                        "healthCheckUrl":"http://172.16.32.10:9798/actuator/health",
                        "vipAddress":"hotel-operation-platform-message",
                        "secureVipAddress":"hotel-operation-platform-message",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1623210814465",
                        "lastDirtyTimestamp":"1623210814258",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-MALL-BOOKING",
                "instance":[
                    {
                        "instanceId":"otm-new:otmgroup-mall-booking:9091",
                        "hostName":"172.16.0.17",
                        "app":"OTMGROUP-MALL-BOOKING",
                        "ipAddr":"172.16.0.17",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9091,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628665656690,
                            "lastRenewalTimestamp":1628758071387,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999210268
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9091"
                        },
                        "homePageUrl":"http://172.16.0.17:9091/",
                        "statusPageUrl":"http://172.16.0.17:9091/otmgroupMallBooking/actuator/info",
                        "healthCheckUrl":"http://172.16.0.17:9091/otmgroupMallBooking/actuator/health",
                        "vipAddress":"otmgroup-mall-booking",
                        "secureVipAddress":"otmgroup-mall-booking",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628665656690",
                        "lastDirtyTimestamp":"1628665656220",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"PMS-HOTEL-DATA-SYNC",
                "instance":[
                    {
                        "instanceId":"172.16.32.4:pms-hotel-data-sync:9678",
                        "hostName":"172.16.32.4",
                        "app":"PMS-HOTEL-DATA-SYNC",
                        "ipAddr":"172.16.32.4",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9678,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628502854442,
                            "lastRenewalTimestamp":1628758054914,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1627985106141
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9678"
                        },
                        "homePageUrl":"http://172.16.32.4:9678/",
                        "statusPageUrl":"http://172.16.32.4:9678/pms-hotel-data-sync/actuator/info",
                        "healthCheckUrl":"http://172.16.32.4:9678/pms-hotel-data-sync/actuator/health",
                        "vipAddress":"pms-hotel-data-sync",
                        "secureVipAddress":"pms-hotel-data-sync",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628502854442",
                        "lastDirtyTimestamp":"1628502854194",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-ADMIN",
                "instance":[
                    {
                        "instanceId":"172.16.32.8:hotel-operation-platform-admin:9796",
                        "hostName":"172.16.32.8",
                        "app":"HOTEL-OPERATION-PLATFORM-ADMIN",
                        "ipAddr":"172.16.32.8",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9796,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1625109970111,
                            "lastRenewalTimestamp":1628758062395,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1623159990707
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9796"
                        },
                        "homePageUrl":"http://172.16.32.8:9796/",
                        "statusPageUrl":"http://172.16.32.8:9796/hotel-operation-platform-admin/actuator/info",
                        "healthCheckUrl":"http://172.16.32.8:9796/hotel-operation-platform-admin/actuator/health",
                        "vipAddress":"hotel-operation-platform-admin",
                        "secureVipAddress":"hotel-operation-platform-admin",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1625109970111",
                        "lastDirtyTimestamp":"1625109969883",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"UNIONBUY-MEMBER",
                "instance":[
                    {
                        "instanceId":"172.16.32.6:unionbuy-member:9092",
                        "hostName":"172.16.32.6",
                        "app":"UNIONBUY-MEMBER",
                        "ipAddr":"172.16.32.6",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9092,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216885,
                            "lastRenewalTimestamp":1628758078335,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999195314
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9092"
                        },
                        "homePageUrl":"http://172.16.32.6:9092/",
                        "statusPageUrl":"http://172.16.32.6:9092/actuator/info",
                        "healthCheckUrl":"http://172.16.32.6:9092/actuator/health",
                        "vipAddress":"unionbuy-member",
                        "secureVipAddress":"unionbuy-member",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216885",
                        "lastDirtyTimestamp":"1621999195306",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-OPENAPI",
                "instance":[
                    {
                        "instanceId":"172.16.32.8:otmgroup-openapi:8881",
                        "hostName":"172.16.32.8",
                        "app":"OTMGROUP-OPENAPI",
                        "ipAddr":"172.16.32.8",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8881,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628668949667,
                            "lastRenewalTimestamp":1628758057047,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1623140586501
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8881"
                        },
                        "homePageUrl":"http://172.16.32.8:8881/",
                        "statusPageUrl":"http://172.16.32.8:8881/actuator/info",
                        "healthCheckUrl":"http://172.16.32.8:8881/actuator/health",
                        "vipAddress":"otmgroup-openapi",
                        "secureVipAddress":"otmgroup-openapi",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628668949667",
                        "lastDirtyTimestamp":"1628668949530",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-MALL-SERVER",
                "instance":[
                    {
                        "instanceId":"${spring.cloud.client.ipAddress}:9827",
                        "hostName":"172.16.0.17",
                        "app":"OTMGROUP-MALL-SERVER",
                        "ipAddr":"172.16.0.17",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9827,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1627896666372,
                            "lastRenewalTimestamp":1628758062163,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1625828713867
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9827"
                        },
                        "homePageUrl":"http://172.16.0.17:9827/",
                        "statusPageUrl":"http://172.16.0.17:9827/actuator/info",
                        "healthCheckUrl":"http://172.16.0.17:9827/actuator/health",
                        "vipAddress":"otmgroup-mall-server",
                        "secureVipAddress":"otmgroup-mall-server",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1627896666372",
                        "lastDirtyTimestamp":"1627896666082",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-POINTS",
                "instance":[
                    {
                        "instanceId":"172.16.32.10:hotel-operation-platform-points:9528",
                        "hostName":"172.16.32.10",
                        "app":"HOTEL-OPERATION-PLATFORM-POINTS",
                        "ipAddr":"172.16.32.10",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9528,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628582368495,
                            "lastRenewalTimestamp":1628758064167,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999203678
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9528"
                        },
                        "homePageUrl":"http://172.16.32.10:9528/",
                        "statusPageUrl":"http://172.16.32.10:9528/actuator/info",
                        "healthCheckUrl":"http://172.16.32.10:9528/actuator/health",
                        "vipAddress":"hotel-operation-platform-points",
                        "secureVipAddress":"hotel-operation-platform-points",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628582368496",
                        "lastDirtyTimestamp":"1628582368264",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-DEPOSIT",
                "instance":[
                    {
                        "instanceId":"172.16.32.9:otmgroup-deposit:8084",
                        "hostName":"172.16.32.9",
                        "app":"OTMGROUP-DEPOSIT",
                        "ipAddr":"172.16.32.9",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8084,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628562069211,
                            "lastRenewalTimestamp":1628758075550,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1622255219221
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8084"
                        },
                        "homePageUrl":"http://172.16.32.9:8084/",
                        "statusPageUrl":"http://172.16.32.9:8084/actuator/info",
                        "healthCheckUrl":"http://172.16.32.9:8084/actuator/health",
                        "vipAddress":"otmgroup-deposit",
                        "secureVipAddress":"otmgroup-deposit",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628562069211",
                        "lastDirtyTimestamp":"1628562069019",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-AUTH",
                "instance":[
                    {
                        "instanceId":"172.16.32.8:hotel-operation-platform-auth:9040",
                        "hostName":"172.16.32.8",
                        "app":"HOTEL-OPERATION-PLATFORM-AUTH",
                        "ipAddr":"172.16.32.8",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9040,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1627957561772,
                            "lastRenewalTimestamp":1628758054809,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1623134071109
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9040"
                        },
                        "homePageUrl":"http://172.16.32.8:9040/",
                        "statusPageUrl":"http://172.16.32.8:9040/actuator/info",
                        "healthCheckUrl":"http://172.16.32.8:9040/actuator/health",
                        "vipAddress":"hotel-operation-platform-auth",
                        "secureVipAddress":"hotel-operation-platform-auth",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1627957561772",
                        "lastDirtyTimestamp":"1627957561583",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"REGISTER",
                "instance":[
                    {
                        "instanceId":"${spring.cloud.client.ipAddress}:9100",
                        "hostName":"172.16.0.11",
                        "app":"REGISTER",
                        "ipAddr":"172.16.0.11",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9100,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216603,
                            "lastRenewalTimestamp":1628758048475,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999216603
                        },
                        "metadata":{
                            "management.port":"9100"
                        },
                        "homePageUrl":"http://172.16.0.11:9100/",
                        "statusPageUrl":"http://172.16.0.11:9100/actuator/info",
                        "healthCheckUrl":"http://172.16.0.11:9100/actuator/health",
                        "vipAddress":"register",
                        "secureVipAddress":"register",
                        "isCoordinatingDiscoveryServer":"true",
                        "lastUpdatedTimestamp":"1621999216603",
                        "lastDirtyTimestamp":"1621999216594",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"UNIONBUY-GOOD-LIFENG",
                "instance":[
                    {
                        "instanceId":"172.16.0.17:unionbuy-good-lifeng:9060",
                        "hostName":"172.16.0.17",
                        "app":"UNIONBUY-GOOD-LIFENG",
                        "ipAddr":"172.16.0.17",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9060,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216881,
                            "lastRenewalTimestamp":1628758058767,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999193419
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9060"
                        },
                        "homePageUrl":"http://172.16.0.17:9060/",
                        "statusPageUrl":"http://172.16.0.17:9060/actuator/info",
                        "healthCheckUrl":"http://172.16.0.17:9060/actuator/health",
                        "vipAddress":"unionbuy-good-lifeng",
                        "secureVipAddress":"unionbuy-good-lifeng",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216881",
                        "lastDirtyTimestamp":"1621999193412",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-MALL-PRODUCT",
                "instance":[
                    {
                        "instanceId":"172.16.32.4:otmgroup-mall-product:8090",
                        "hostName":"172.16.32.4",
                        "app":"OTMGROUP-MALL-PRODUCT",
                        "ipAddr":"172.16.32.4",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8090,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628674768145,
                            "lastRenewalTimestamp":1628758055075,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1623811109005
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8090"
                        },
                        "homePageUrl":"http://172.16.32.4:8090/",
                        "statusPageUrl":"http://172.16.32.4:8090/mall-product/actuator/info",
                        "healthCheckUrl":"http://172.16.32.4:8090/mall-product/actuator/health",
                        "vipAddress":"otmgroup-mall-product",
                        "secureVipAddress":"otmgroup-mall-product",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628674768145",
                        "lastDirtyTimestamp":"1628674768026",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-SERVER",
                "instance":[
                    {
                        "instanceId":"172.16.32.9:hotel-operation-platform-server:9797",
                        "hostName":"172.16.32.9",
                        "app":"HOTEL-OPERATION-PLATFORM-SERVER",
                        "ipAddr":"172.16.32.9",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9797,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628663434856,
                            "lastRenewalTimestamp":1628758062773,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1627467998295
                        },
                        "metadata":{
                            "result-code-key":"resultCode",
                            "result-msg-key":"resultMsg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9797"
                        },
                        "homePageUrl":"http://172.16.32.9:9797/",
                        "statusPageUrl":"http://172.16.32.9:9797/actuator/info",
                        "healthCheckUrl":"http://172.16.32.9:9797/actuator/health",
                        "vipAddress":"hotel-operation-platform-server",
                        "secureVipAddress":"hotel-operation-platform-server",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628663434856",
                        "lastDirtyTimestamp":"1628663434625",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"UNIONBUY-ADMIN",
                "instance":[
                    {
                        "instanceId":"172.16.32.6:unionbuy-admin:8089",
                        "hostName":"172.16.32.6",
                        "app":"UNIONBUY-ADMIN",
                        "ipAddr":"172.16.32.6",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8089,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999212765,
                            "lastRenewalTimestamp":1628758074172,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999212765
                        },
                        "metadata":{
                            "management.port":"8089"
                        },
                        "homePageUrl":"http://172.16.32.6:8089/",
                        "statusPageUrl":"http://172.16.32.6:8089/actuator/info",
                        "healthCheckUrl":"http://172.16.32.6:8089/actuator/health",
                        "vipAddress":"unionbuy-admin",
                        "secureVipAddress":"unionbuy-admin",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999212765",
                        "lastDirtyTimestamp":"1621999212761",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-BOOKING",
                "instance":[
                    {
                        "instanceId":"172.16.32.8:hotel-operation-platform-booking:8787",
                        "hostName":"172.16.32.8",
                        "app":"HOTEL-OPERATION-PLATFORM-BOOKING",
                        "ipAddr":"172.16.32.8",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8787,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628757104701,
                            "lastRenewalTimestamp":1628758064570,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1626077756783
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"message",
                            "no-auth-code":"200",
                            "common-error-code":"300",
                            "management.port":"8787"
                        },
                        "homePageUrl":"http://172.16.32.8:8787/",
                        "statusPageUrl":"http://172.16.32.8:8787/actuator/info",
                        "healthCheckUrl":"http://172.16.32.8:8787/actuator/health",
                        "vipAddress":"hotel-operation-platform-booking",
                        "secureVipAddress":"hotel-operation-platform-booking",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628757104701",
                        "lastDirtyTimestamp":"1628757104416",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-MERCHANT-EXTERNAL-ABILITY",
                "instance":[
                    {
                        "instanceId":"172.16.32.6:otmgroup-merchant-external-ability:9199",
                        "hostName":"172.16.32.6",
                        "app":"OTMGROUP-MERCHANT-EXTERNAL-ABILITY",
                        "ipAddr":"172.16.32.6",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9199,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1624533155789,
                            "lastRenewalTimestamp":1628758074172,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1624413143638
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9199"
                        },
                        "homePageUrl":"http://172.16.32.6:9199/",
                        "statusPageUrl":"http://172.16.32.6:9199/merchantExtAbility/actuator/info",
                        "healthCheckUrl":"http://172.16.32.6:9199/merchantExtAbility/actuator/health",
                        "vipAddress":"otmgroup-merchant-external-ability",
                        "secureVipAddress":"otmgroup-merchant-external-ability",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1624533155790",
                        "lastDirtyTimestamp":"1624533155524",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"UNIONBUY-SERVER",
                "instance":[
                    {
                        "instanceId":"172.16.32.6:unionbuy-server:9096",
                        "hostName":"172.16.32.6",
                        "app":"UNIONBUY-SERVER",
                        "ipAddr":"172.16.32.6",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9096,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216883,
                            "lastRenewalTimestamp":1628758074172,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999195309
                        },
                        "metadata":{
                            "result-code-key":"message",
                            "no-auth-code":"200",
                            "common-error-code":"300",
                            "management.port":"9096"
                        },
                        "homePageUrl":"http://172.16.32.6:9096/",
                        "statusPageUrl":"http://172.16.32.6:9096/actuator/info",
                        "healthCheckUrl":"http://172.16.32.6:9096/actuator/health",
                        "vipAddress":"unionbuy-server",
                        "secureVipAddress":"unionbuy-server",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216883",
                        "lastDirtyTimestamp":"1621999195303",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-DISTRIBUTION",
                "instance":[
                    {
                        "instanceId":"172.16.32.4:otmgroup-distribution:9555",
                        "hostName":"172.16.32.4",
                        "app":"OTMGROUP-DISTRIBUTION",
                        "ipAddr":"172.16.32.4",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9555,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628653207977,
                            "lastRenewalTimestamp":1628758067208,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1623128805497
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9555"
                        },
                        "homePageUrl":"http://172.16.32.4:9555/",
                        "statusPageUrl":"http://172.16.32.4:9555/otmgroup-distribution/actuator/info",
                        "healthCheckUrl":"http://172.16.32.4:9555/otmgroup-distribution/actuator/health",
                        "vipAddress":"otmgroup-distribution",
                        "secureVipAddress":"otmgroup-distribution",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628653207977",
                        "lastDirtyTimestamp":"1628653207809",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-DATA-PROCESSING-ABILITY",
                "instance":[
                    {
                        "instanceId":"172.16.32.9:otmgroup-data-processing-ability:9093",
                        "hostName":"172.16.32.9",
                        "app":"OTMGROUP-DATA-PROCESSING-ABILITY",
                        "ipAddr":"172.16.32.9",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9093,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628649523038,
                            "lastRenewalTimestamp":1628758071821,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999195682
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9093"
                        },
                        "homePageUrl":"http://172.16.32.9:9093/",
                        "statusPageUrl":"http://172.16.32.9:9093/actuator/info",
                        "healthCheckUrl":"http://172.16.32.9:9093/actuator/health",
                        "vipAddress":"otmgroup-data-processing-ability",
                        "secureVipAddress":"otmgroup-data-processing-ability",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628649523038",
                        "lastDirtyTimestamp":"1628649522892",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"UNIONBUY-GOODS",
                "instance":[
                    {
                        "instanceId":"172.16.32.6:unionbuy-goods:9089",
                        "hostName":"172.16.32.6",
                        "app":"UNIONBUY-GOODS",
                        "ipAddr":"172.16.32.6",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9089,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216884,
                            "lastRenewalTimestamp":1628758074172,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999195313
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9089"
                        },
                        "homePageUrl":"http://172.16.32.6:9089/",
                        "statusPageUrl":"http://172.16.32.6:9089/actuator/info",
                        "healthCheckUrl":"http://172.16.32.6:9089/actuator/health",
                        "vipAddress":"unionbuy-goods",
                        "secureVipAddress":"unionbuy-goods",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216884",
                        "lastDirtyTimestamp":"1621999195306",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"APOLLO-CONFIGSERVICE",
                "instance":[
                    {
                        "instanceId":"172.16.0.11:apollo-configservice:9090",
                        "hostName":"172.16.0.11",
                        "app":"APOLLO-CONFIGSERVICE",
                        "ipAddr":"172.16.0.11",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9090,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999205316,
                            "lastRenewalTimestamp":1628758076324,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999205316
                        },
                        "metadata":{
                            "management.port":"9090"
                        },
                        "homePageUrl":"http://172.16.0.11:9090/",
                        "statusPageUrl":"http://172.16.0.11:9090/info",
                        "healthCheckUrl":"http://172.16.0.11:9090/health",
                        "vipAddress":"apollo-configservice",
                        "secureVipAddress":"apollo-configservice",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999205316",
                        "lastDirtyTimestamp":"1621999205308",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-COUPON",
                "instance":[
                    {
                        "instanceId":"hotel-operation-platform-coupon:9333",
                        "hostName":"172.16.32.5",
                        "app":"HOTEL-OPERATION-PLATFORM-COUPON",
                        "ipAddr":"172.16.32.5",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9333,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628506040709,
                            "lastRenewalTimestamp":1628758061530,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1627464197306
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"9333"
                        },
                        "homePageUrl":"http://172.16.32.5:9333/",
                        "statusPageUrl":"http://172.16.32.5:9333/hotel-operation-platform-coupon/actuator/info",
                        "healthCheckUrl":"http://172.16.32.5:9333/hotel-operation-platform-coupon/actuator/health",
                        "vipAddress":"hotel-operation-platform-coupon",
                        "secureVipAddress":"hotel-operation-platform-coupon",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628506040709",
                        "lastDirtyTimestamp":"1628506040520",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"HOTEL-OPERATION-PLATFORM-BALANCE",
                "instance":[
                    {
                        "instanceId":"172.16.32.9:hotel-operation-platform-balance:9999",
                        "hostName":"172.16.32.9",
                        "app":"HOTEL-OPERATION-PLATFORM-BALANCE",
                        "ipAddr":"172.16.32.9",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":9999,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1628757959333,
                            "lastRenewalTimestamp":1628757959333,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1622271459024
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"message",
                            "no-auth-code":"200",
                            "common-error-code":"300",
                            "management.port":"9999"
                        },
                        "homePageUrl":"http://172.16.32.9:9999/",
                        "statusPageUrl":"http://172.16.32.9:9999/actuator/info",
                        "healthCheckUrl":"http://172.16.32.9:9999/actuator/health",
                        "vipAddress":"hotel-operation-platform-balance",
                        "secureVipAddress":"hotel-operation-platform-balance",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1628757959333",
                        "lastDirtyTimestamp":"1628757959031",
                        "actionType":"ADDED"
                    }
                ]
            },
            {
                "name":"OTMGROUP-WECHAT-ABILITY",
                "instance":[
                    {
                        "instanceId":"172.16.32.10:otmgroup-wechat-ability:8077",
                        "hostName":"172.16.32.10",
                        "app":"OTMGROUP-WECHAT-ABILITY",
                        "ipAddr":"172.16.32.10",
                        "status":"UP",
                        "overriddenStatus":"UNKNOWN",
                        "port":{
                            "$":8077,
                            "@enabled":"true"
                        },
                        "securePort":{
                            "$":443,
                            "@enabled":"false"
                        },
                        "countryId":1,
                        "dataCenterInfo":{
                            "@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                            "name":"MyOwn"
                        },
                        "leaseInfo":{
                            "renewalIntervalInSecs":30,
                            "durationInSecs":90,
                            "registrationTimestamp":1621999216123,
                            "lastRenewalTimestamp":1628758054424,
                            "evictionTimestamp":0,
                            "serviceUpTimestamp":1621999216123
                        },
                        "metadata":{
                            "result-code-key":"code",
                            "result-msg-key":"msg",
                            "no-auth-code":"440",
                            "common-error-code":"300",
                            "management.port":"8077"
                        },
                        "homePageUrl":"http://172.16.32.10:8077/",
                        "statusPageUrl":"http://172.16.32.10:8077/actuator/info",
                        "healthCheckUrl":"http://172.16.32.10:8077/actuator/health",
                        "vipAddress":"otmgroup-wechat-ability",
                        "secureVipAddress":"otmgroup-wechat-ability",
                        "isCoordinatingDiscoveryServer":"false",
                        "lastUpdatedTimestamp":"1621999216123",
                        "lastDirtyTimestamp":"1621999216118",
                        "actionType":"ADDED"
                    }
                ]
            }
        ]
    }
}`

	fmt.Println(data)
}

func TestEq(t *testing.T) {
	s1:= "hello"
	s2:="hello"
	fmt.Println(s1==s2)
}


